### ISSUE TITLE
modularize dcli file into smaller ones

### ISSUE THREAD

**Issue by nurdtechie98** [nurdtechie98/drive-cli#10]
split dcli.py into smaller files, break the files into smaller files by creating new smaller files for each similar command.

**Comment by raghav-dalmia** [comment]
I would like to solve this issue. Can I? @nurdtechie98

**Comment by nurdtechie98** [comment]
Sure go ahead. Be careful in the file structure cos the changes are going to be critical

**Comment by raghav-dalmia** [comment]
ok, I will try to make a simple file structure a possible.

**Comment by inishchith** [comment]
@raghav-dalmia Sure. Please do update this thread or open a PR referencing this issue. We can have further discussion over there ;)

**Comment by raghav-dalmia** [comment]
@inishchith sorry for late reply. I have made a package name subcommand which contains one module for each command. please check it [here](https://github.com/nurdtechie98/drive-cli/files/2930328/drive_cli.zip). I have tested it on a local computer and get a positive response. Also, I have opened a PR for the same, please check it out.
