### ISSUE TITLE
drive push doesn't delete locally deleted remote GDrive files

### ISSUE THREAD

**Issue by okliv** [nurdtechie98/drive-cli#103]
When i delete local files and then run `drive push` i expect that remote files will be deleted too but they are still in it's place

is it expected behaviour?

and if i delete files in GDrive folder (move it to trash) it doesn't see any changes unless i clean up a trash

**Comment by nurdtechie98** [comment]
Hey @okliv, as of now we have the drive rm for removing the files deleted, this is an expected behaviour, something that should be added. 
I hope it answers your query
Thanks for bringing it to notice 👍

**Comment by okliv** [comment]
semantically `push` is analog from `git`. and `git` make a mirror-copy of pushed changes (after `checkout`). but here we need to `push`, then list remote (recursively?), then compare and `rm` manually? then I'd suggested change `push` to something less "git-ish" like `upload`

(and `rm`, btw, is from `cli` ... for me this mix of semantics is little bit misleading)
