### ISSUE TITLE
Can't login into my account

### ISSUE THREAD

**Issue by PaPablo** [nurdtechie98/drive-cli#104]
Google tells me I can't login because the app isn't verified yet

**Comment by saucesaft** [comment]
I am having the same error.

**Comment by nurdtechie98** [comment]
Hey, @PaPablo @saucesaft  to verify the app I need a verified domain name as per the latest rules of google api's I am in the process for the same.
You can build your own copy from the source and start using drive-cli until then.
Sorry for the inconvenience caused.
