### ISSUE TITLE
Some comments on commands and options

### ISSUE THREAD

**Issue by jean** [nurdtechie98/drive-cli#12]
> #adding the file or folder inside particular parent file(test) using its file id
> $ drive add_remote --file mailer.py --pid 1RJOWpW5MuP9RXpgZbp9OdauhaBtJd49g

`pid` in command-line context more familiarly means "process id". I'd prefer `parent-id`. 

The help text sounds like you can add a file inside a **file**, that doesn't seem to make sense, should be _folder_?

> - `view-files`: list your files; filter them by name, type.

Rather `query` or `search`. And then rename the `cat` command to `view-file` :wink: 

> - `add_remote`: upload existing local file to drive and get it linked.

Just `add`, remote is implied. Also, "remote" here invites confusion with git remote.

> - `status`: list changes made to local files since last pull or pull.

Also shows files updated remotely?

**Comment by inishchith** [comment]
@jean 
> pid in command-line context more familiarly means "process id". I'd prefer parent-id.
- Makes sense but IMO it's a convention to check the help text ( for first timers atleast ) where it clearly states the usage, I that case i'd prefer a `pid`.

- Also, quick note @nurdtechie98 :
```
  --pid TEXT   specify particular folder id/sharing_link of the folder under
               which remote must must be added
```
  It'd be easier to understand if the help text is just - ` specify particular folder id/sharing_link under which remote must must be added `.


@nurdtechie98 pinging you, here.
Let me know what you think of these.

Thanks

**Comment by inishchith** [comment]
@jean Closing this for now.
Feel free to open in case you feel something is wrongly interpreted / addressed ;)

**Comment by jean** [comment]
@inishchith I'm fine with your preference regarding `pid`, it isn't ambiguous in the context of this program. 
I do think it's an easy-to-avoid false rhyme with usage elsewhere, and I think it's less explicit than it needs to be (`parent-id` is self-documenting). 

I'm a bit disappointed you don't respond to the other suggestions:

> > * `view-files`: list your files; filter them by name, type.
> Rather `query` or `search`. And then rename the `cat` command to `view-file` wink

`cat` is a terrible name for "view-file". If ever there was a Un*x fossil, that's one. I.e. you disregard the meaning of `pid` elsewhere (in all the process management tools like `kill`, `ps`, `top`, etc.), but for `cat` you rely on the reader's familiarity with a common usage of the old tool (where `more` or `less` is actually normally more appropriate). The expansion (_concatenate_) doesn't even make sense. I mean, I love the ancient nerd humour of the cryptic old Un*x commands, but we're in different times now, we're all juggling myriads of new tools from all over the place, and clear boring naming is a big help.  

`view-files` also does not imply any filtering. `filter`/`query`/`search` does. 

> > * `add_remote`: upload existing local file to drive and get it linked.
> Just `add`, remote is implied. Also, "remote" here invites confusion with git remote.

I stand by that, I don't see that `_remote` adds anything.

Since there aren't any collisions, the old names can silently keep working for the sake of backwards compatibility.
