### ISSUE TITLE
add share functionality

### ISSUE THREAD

**Issue by nurdtechie98** [nurdtechie98/drive-cli#15]
one should be able to share and give access to files directly from the cli

**Comment by raghav-dalmia** [comment]
@nurdtechie98 I want to work on this issue. can I?

**Comment by raghav-dalmia** [comment]
Please let me know. Can I work on this issue?

**Comment by nurdtechie98** [comment]
sure @raghav-dalmia go ahead with it

**Comment by raghav-dalmia** [comment]
Please give clarification about this issue, I have to generate a share link or take email id as argument and share file to that person?

**Comment by nurdtechie98** [comment]
@raghav-dalmia provide both the options by specifying particular flag for each.
