### ISSUE TITLE
add revisions functionality 

### ISSUE THREAD

**Issue by nurdtechie98** [nurdtechie98/drive-cli#16]
add the view revision history option, which provides dates and time of documents previous revisions

**Comment by raghav-dalmia** [comment]
I want to work on this issue.

**Comment by nurdtechie98** [comment]
Sure Go ahead @raghav-dalmia 👍

**Comment by raghav-dalmia** [comment]
@nurdtechie98 please specify exactly what feature should this functionality have?

**Comment by nurdtechie98** [comment]
yes something like that. like we have `git status`  would be great.

**Comment by raghav-dalmia** [comment]
I didn't get your point, exactly what you want which is similar to `git status`. I think we have a `drive status ` command for that purpose.

**Comment by inishchith** [comment]
@raghav-dalmia I guess @nurdtechie98 meant `git log`

**Comment by raghav-dalmia** [comment]
Date/Time
    Cwd
    Command
    Mandatory Argument [if any]
    Flags [list] [if any]
        argument/input taken by each flag
    other inputs [like email id as in share option]```

I am going to store that much data and will in the same manner. 
If it requires any changes, please let me know.

**Comment by nurdtechie98** [comment]
What exactly do you mean by Command here @raghav-dalmia ?

**Comment by raghav-dalmia** [comment]
Command like `drive (login, logout, ls, cat, share)`...

**Comment by raghav-dalmia** [comment]
Something like this

**Comment by nurdtechie98** [comment]
@raghav-dalmia I guess there is some sort of mis-understanding. what I mean by revisions is not when which commands was used rather history of a file or folder. When a particular was modified using [revision](https://developers.google.com/drive/api/v3/manage-revisions) feature of drive.

**Comment by raghav-dalmia** [comment]
ok, got your point. So can I create a new issue for my PR?

**Comment by nurdtechie98** [comment]
@inishchith @sauravchirania @shivam1708, what do you think about the feature added by @raghav-dalmia ?

**Comment by nurdtechie98** [comment]
I have mixed feelings on its use-case 🙈.

**Comment by shivam1708** [comment]
The details about which command was used when doesn't seem important to me, but it can be used just as an add-on if you want to

**Comment by raghav-dalmia** [comment]
> I have mixed feelings on its use-case .
> For now adding the expected feature up-for-grab

I will do that too, please give me some time.

**Comment by nurdtechie98** [comment]
@raghav-dalmia take it easy, we understand there has been a misunderstanding. We'll discuss the Pr raised as well. Do you want to work on the original issue ?

**Comment by raghav-dalmia** [comment]
Yes

**Comment by nurdtechie98** [comment]
Sure @raghav-dalmia, go ahead keep its name as `drive log` then for now lets keep history keyword for what you have raised a PR.

**Comment by raghav-dalmia** [comment]
ok, @nurdtechie98

**Comment by raghav-dalmia** [comment]
@nurdtechie98  please review the PR, I have added revision functionality to it.
