### ISSUE TITLE
use library for mimetypes

### ISSUE THREAD

**Issue by nurdtechie98** [nurdtechie98/drive-cli#17]
remove the manually written dict of mimetypes in utils.py and use some library to extract the mimetype from file extension.

**Comment by adtyanair** [comment]
I would like to work on this issue. I have found a library called [mimetypes](https://docs.python.org/3/library/mimetypes.html) in python which provides this functionality. I'll try implementing this.

**Comment by inishchith** [comment]
@adtyanair sure :+1: go ahead

**Comment by nurdtechie98** [comment]
@adtyanair just remember, you need to wait till 28th of Feb as per the timeline for the official coding period to begin.

**Comment by adtyanair** [comment]
I tried implementing the mimetypes library, but it's not returning all file types as in the utils.py file.
for example: for `.zip` file,  the library returns `application/zip` but it is `application/x-zip-compressed` in the utils file
