### ISSUE TITLE
Issue with cat command

### ISSUE THREAD

**Issue by raghav-dalmia** [nurdtechie98/drive-cli#18]
I create a dummy folder on my drive and test `drive cat ` command on that folder. Terminal show error 

`googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1f5Lhttb1ZdA8fuOxlZo48A-_hZDnu8_w/export?mimeType=application%2Fmsword&alt=media returned "Export only supports Google Docs."`

![screenshot from 2019-02-15 12-12-06](https://user-images.githubusercontent.com/46166767/52839112-f3c20400-311a-11e9-8a7d-45d7a4bda559.png)

 I select **doc**  as the export type, the error still persists.

**Comment by nurdtechie98** [comment]
@raghav-dalmia 
The cat functionality is meant for checking the contents in a file not a folder. 
It is similar to cat command of linux so try cat for files and you'll get the contents of it.
