### ISSUE TITLE
fix get_fid() to work for all the cases

### ISSUE THREAD

**Issue by nurdtechie98** [nurdtechie98/drive-cli#19]
[get_fid()](https://github.com/nurdtechie98/drive-cli/blob/26e6aa856a552ba4eec82501d5d08ba9edd0dfa3/drive_cli/dcli.py#L178) function it works for only limited type of links but gets wrong output on certain cases.
example:
for input 
`
https://drive.google.com/file/d/1NKaxkeqEas9GuKc82Thg6jwDxjyOB7Hn/view?usp=sharing
`
it returns `view` where it is expected to return `1NKaxkeqEas9GuKc82Thg6jwDxjyOB7Hn`

**Comment by Anukriti2512** [comment]
I would like to work on this issue

**Comment by nurdtechie98** [comment]
sure you can work on it. Go ahead:+1:
