### ISSUE TITLE
add unit tests

### ISSUE THREAD

**Issue by adtyanair** [nurdtechie98/drive-cli#21]
Unit tests can help save a lot of time when during testing. Without it, testing seems to be difficult and time consuming as we have to run the whole program through different scenarios manually every time.

**Comment by inishchith** [comment]
@adtyanair True. We (mentors) along with @nurdtechie98 will think of a proper structure and open some issues in coming days.

Thanks for addressing 😄

**Comment by nurdtechie98** [comment]
@adtyanair as discussed in slack we'll split this issue into smaller ones and bring up a proper structure to make it easy for you guys. So closing this issue as for now

**Comment by inishchith** [comment]
@adtyanair This is being worked on.
Closing in reference to #30 .
