### ISSUE TITLE
Change "add_remote" to "add-remote"

### ISSUE THREAD

**Issue by sauravchirania** [nurdtechie98/drive-cli#23]
In the command view-files, the separator between the words view and files is a hyphen. It'll be nice if add_remote follows the same convention for consistency.

So, we need to change the command add_remote to add-remote and update the README accordingly.

**Comment by FredAmartey** [comment]
Hi, id like to work on this. I want to get experience with contributing. Can you show me which file I should be looking at?

**Comment by sauravchirania** [comment]
> Edit: Nvm, found it :) Can i go ahead and fix it?

Sure, go ahead!

**Comment by sauravchirania** [comment]
Fixed in #26.
