### ISSUE TITLE
add requirements.txt or Pipfile

### ISSUE THREAD

**Issue by adtyanair** [nurdtechie98/drive-cli#27]
currently, the only option to install and manage the dependencies is by using the `setup.py`. It'll be easier to manage the dependencies by having a `requirements.txt` or `Pipfile`

**Comment by inishchith** [comment]
@adtyanair Any progress with this?

**Comment by adtyanair** [comment]
I was able to add all the dependencies in the `setup.py` file using `pipenv` and `Pipfile`. I verified this by running `pip install -e .` which shows requirement already satisfied. But to run the program, it is required to install it to the system and this installs the dependencies anyways. 

Also, I looked through some other similar python packages and none of them seems to have a Pipfile. so I'm still researching on this.

**Comment by inishchith** [comment]
@adtyanair Yes, I've had a thought over this. I feel it's be better if we control the versions of  dependencies right from `setup.py`.

I'd really appreciate if you can update the `setup.py` file instead with current versions of the dependencies. I missed this out. Apologies for the late revert.

Let me know what you think

**Comment by inishchith** [comment]
@adtyanair any updates on this?

**Comment by adtyanair** [comment]
as of now, the dependency versions are not provided and available latest versions are being installed. This could break something if a breaking change is added to any of the dependencies. 

At the moment the following versions are being installed(on Linux) and drive seems to work properly with these:
```
click [required: Any, installed: 7.0]
colorama [required: Any, installed: 0.4.1]
google-api-python-client [required: Any, installed: 1.7.8]
httplib2 [required: Any, installed: 0.12.1]
oauth2client [required: Any, installed: 4.1.3]
pick [required: Any, installed: 0.6.4]
prettytable [required: Any, installed: 0.7.2]
pyfiglet [required: Any, installed: 0.8.post1]
requests [required: Any, installed: 2.21.0]
```
Should I fix these versions for the dependencies?

**Comment by inishchith** [comment]
@adtyanair Sorry for addressing you comments lately. Sure, Go ahead.
Thanks :)

**Comment by adtyanair** [comment]
I have created a pull request. But I was not able to do anything about the requirement 'windows-curses' because I don't have a windows system with me. It would be nice if someone with a windows system could help.
