### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by Avni-Sharma** [nurdtechie98/drive-cli#28]
[status: list changes made to local files since last pull or pull.
](https://github.com/nurdtechie98/drive-cli#features)
I guess it should be last push or pull

**Comment by nurdtechie98** [comment]
yes, @Avni-Sharma it should be fixed

**Comment by Avni-Sharma** [comment]
Hi. Is there any way where I can pick up the specific commit for Readme. My previous commits are also coming with this commit. Please  refer #33

**Comment by nurdtechie98** [comment]
@Avni-Sharma no that can't be done. What could be done instead, is you can create a separate branch and then make only the required changes to it and raise a pull request from that.

**Comment by aakankshadhurandhar** [comment]
hello i want to get started on it how to get started.

**Comment by nurdtechie98** [comment]
Hi @aakankshadhurandhar welcome to Drive-Cli. For the start you should try installing drive CLI for development using the instructions in [readme](https://github.com/nurdtechie98/drive-cli#installation).
Once you are done with that try out the various commands and make an effort to understand how these things work.
After that you can look for bugs in the code or any issue over here and make a claim to work on it😊.
For any further queries feel free to ping us anytime on the slack channel and we'll help you out.

**Comment by Manvityagi** [comment]
Why is this issue up for grab? This typo: "status: list changes made to local files since last pull or pull." hasn't been corrected yet.

**Comment by Avni-Sharma** [comment]
I have raised a PR . Need to correct it

**Comment by Manvityagi** [comment]
Yeahh...u have raised a pr already,  now nobody else shall claim it kno ?
