### ISSUE TITLE
Complete Usage section of readme

### ISSUE THREAD

**Issue by nurdtechie98** [nurdtechie98/drive-cli#3]
Only a limited number of commands have been added at the moment to usage section. Add all the commands and their corresponding explanations.

**Comment by ahegde3** [comment]
get_file            Gets the specified file from the drive
delete_file       Deletes the specified file.
create_dir        creates a new file directory in the drive

**Comment by swathi-0901** [comment]
I would like to work on this issue , can I..?

**Comment by nurdtechie98** [comment]
Sure, Go ahead👍🏻

**Comment by aakankshadhurandhar** [comment]
i would like to work on this issue

**Comment by nurdtechie98** [comment]
@swathi-0901 @aakankshadhurandhar as discussed in slack channel, we'll be closing this issue for now as we have decided to remove the usage section from readme rather we'll add a wiki section where you guys can then contribute to.
