### ISSUE TITLE
Refresh auth tokens once found expired or invalid

### ISSUE THREAD

**Issue by inishchith** [nurdtechie98/drive-cli#31]
- `Current scenario`:
   * Once logged in, if the user tries any feature after the expiry period i.e `1 hour`, the user has to authenticate him/her self.

- `Expected behaviour`:
   * In order to solve this, we can use `refresh_token` with the help of which once the key found available but invalid or expired, the dependent methods should call `refresh()` method and refresh the token.

- Current progress on this issue 
    * `refresh()` method is yet to be merged which can be found here. #30 .

Feel free to ask doubts.

**Comment by raghav-dalmia** [comment]
@inishchith please give a brief of this issue. I didn't get your point. Thank you

**Comment by inishchith** [comment]
@raghav-dalmia Sorry for the delayed response. 
IMO the description is pretty much clear. Only thing being, this feature is already being employed in the current system ( I found this out a bit later ). Sorry for raising this issue.
Thanks for your interest :)  Closing this for now
