### ISSUE TITLE
Undefined name 'link' in  drive_cli/dcli.py

### ISSUE THREAD

**Issue by cclauss** [nurdtechie98/drive-cli#4]
__link__ is an _undefined name_ in __get_fid()__ which has the potential to raise NameError at runtime.

[flake8](http://flake8.pycqa.org) testing of https://github.com/nurdtechie98/drive-cli on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./drive_cli/dcli.py:170:22: F821 undefined name 'link'
        if 'open' in link:
                     ^
./drive_cli/dcli.py:171:19: F821 undefined name 'link'
            fid = link.split('=')[-1]
                  ^
./drive_cli/dcli.py:173:19: F821 undefined name 'link'
            fid = link.split('/')[-1].split('?')[0]
                  ^
3     F821 undefined name 'link'
3
```

__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by nurdtechie98** [comment]
fixed:+1:  Try now and close the issue once checked.

**Comment by cclauss** [comment]
[flake8](http://flake8.pycqa.org) testing of https://github.com/nurdtechie98/drive-cli on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./drive_cli/dcli.py:135:28: F821 undefined name 'drive_timefloat'
    print(time.time(),"||",drive_timefloat(19800.00),"||",local_time,"||",sync_time)
                           ^
1     F821 undefined name 'drive_timefloat'
1
```
