### ISSUE TITLE
add drive info functionality

### ISSUE THREAD

**Issue by nurdtechie98** [nurdtechie98/drive-cli#40]
Using the command by either specifying the sharing link or the file id one should be able to view relevant information of the file/folder like size of it, members / owners, mimetype , creation date, last modified date, parent folder etc.
Note: The data displayed regarding the same should be organised and layout should be clean enough to read.

**Comment by raghav-dalmia** [comment]
I want to work on this issue. @nurdtechie98

**Comment by inishchith** [comment]
@raghav-dalmia Sure, go ahead ;)

**Comment by raghav-dalmia** [comment]
![Screenshot from 2019-03-20 13-28-56](https://user-images.githubusercontent.com/46166767/54668315-9e5f8500-4b14-11e9-8190-c7e6258506a3.png)
![Screenshot from 2019-03-20 13-29-03](https://user-images.githubusercontent.com/46166767/54668395-cd75f680-4b14-11e9-8c45-3ee2501d7c97.png)

I am going to use the above format to print file info. If it needs any changes please let me know.

**Comment by raghav-dalmia** [comment]
So, I think it's perfect. Can i proceed with this one?

**Comment by raghav-dalmia** [comment]
@nurdtechie98 @inishchith @parulagg27 @sauravchirania @shivam1708 please reply.

**Comment by nurdtechie98** [comment]
@raghav-dalmia sorry for the late reply, I think there is no need of revision, cause we have specific command for it, other than that rest of them looks good.

**Comment by raghav-dalmia** [comment]
ok @nurdtechie98
