### ISSUE TITLE
command line authorize 

### ISSUE THREAD

**Issue by hjyoung1** [nurdtechie98/drive-cli#43]
Is it possible to authorize this in command line only no (gui browser) as i am using it on server which has no gui installed.

**Comment by nurdtechie98** [comment]
Hey @hjyoung1 yes you can do.
Use `drive login --remote` this will give another link which you can open on other device so the login procedure and give the authorization pin back to the server.

**Comment by hjyoung1** [comment]
My bad i was using pip version which didn't have -- remote option
Now using development build it's working now thanks.
