### ISSUE TITLE
share file to multiple user at a time

### ISSUE THREAD

**Issue by raghav-dalmia** [nurdtechie98/drive-cli#50]
`share` function should able to take email of multiple users and share the file with all of them.

**Comment by inishchith** [comment]
@raghav-dalmia Sorry for the delayed response. You can start working on this. 
Thanks.

**Comment by raghav-dalmia** [comment]
at this time I am focusing on google doc's issue. I will do it later. If someone wants to solve this issue can solve it after taking permissions from collaborators.

**Comment by raghav-dalmia** [comment]
I also solve this issue.
