### ISSUE TITLE
[maintenance] Mark issues as stale after prolonged delay

### ISSUE THREAD

**Issue by inishchith** [nurdtechie98/drive-cli#64]
We can close down unresolved issues/bug reports after no proof of reproduction with the help of [Probot Stale](https://github.com/probot/stale) with proper configuration and appropriate description and labels.

@nurdtechie98 Do have a look, Let me know what you think.

[ Open for discussion on configuration file ]

**Comment by nurdtechie98** [comment]
@inishchith we can go ahead with this.
