### ISSUE TITLE
add .driveignore functionality

### ISSUE THREAD

**Issue by nurdtechie98** [nurdtechie98/drive-cli#9]
add functionality that allows users to specify to prevent certain files from getting uploaded

**Comment by SukhnandanMalhotra** [comment]
Can I work on this issue?

**Comment by inishchith** [comment]
@SukhnandanMalhotra Sure, go ahead.

**Comment by SukhnandanMalhotra** [comment]
@inishchith Could you please clarify on how should I approach this issue?

**Comment by inishchith** [comment]
@SukhnandanMalhotra Sure. 
For starters add some file names under `.driveignore` file and on every `push / upload` file action, we can call a `get_ignored_unignored` method which takes in list of `files to upload` ( via methods mentioned below ) and returns two lists:
1. files to that shouldn't be ignored 
2. files that need to be ignored. 

- Methods that might be affected:
  - `create_remote()`:
  - `list_out()`: 
  - `status()`
  - `push()`

**Note:**
- `verbosity` : Make sure you list down ignored files wherever needed.
   - For eg. in case of `create_remote` method, it'd be better if the user can have a view of what files were ignored while uploading at the end of the process.

This much  should be sufficient. You can shape this up in a better way.

Follow up: IMO we can continue work on enhancing the `get_ignored_unignored` method by handling regex of file system, etc. Just like we mention in `.gitignore` after some minimal work gets done.

let me know what you think ;)

**Comment by inishchith** [comment]
@SukhnandanMalhotra Any progress with this?

**Comment by inishchith** [comment]
@SukhnandanMalhotra Any progress on this?

**Comment by raghav-dalmia** [comment]
@nurdtechie98  i want to solve on this issue

**Comment by nurdtechie98** [comment]
@raghav-dalmia, sure just wait for a day if @SukhnandanMalhotra replies else go ahead with it.

**Comment by raghav-dalmia** [comment]
can I proceed? @nurdtechie98

**Comment by nurdtechie98** [comment]
Sure go ahead!!
